import "./globals.css";
import { Space_Mono } from "next/font/google";
const space_mono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"]})
export const metadata = {
  title: "Gradients",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={space_mono.className}>{children}</body>
    </html>
  );
}
